services:
  backend:
    image: 565855251853.dkr.ecr.eu-central-1.amazonaws.com/cracked-pillars-backend:latest
    container_name: cracked-pillars-backend
    volumes:
      - ./hammer/hammer.db3:/app/data/hammer.db3
    environment:
      - RUST_LOG=debug
    env_file: ./hammer/.env.production
    restart: unless-stopped
    healthcheck:
      test: [CMD, curl, -f, http://localhost:8000/health]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  frontend:
    image: 565855251853.dkr.ecr.eu-central-1.amazonaws.com/cracked-pillars-frontend:latest
    container_name: cracked-pillars-frontend
    env_file: ./chisel/.env.production
    ports:
      - 3000:3000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

