services:
  # Backend service (Rust API)
  backend:
    build:
      context: .
      dockerfile: hammer/Dockerfile
    container_name: hammer-backend
    ports:
      - "8001:8000"
    volumes:
      # Mount the JSON data files for easy updates
      - ./quarry/post_processed_abilities.json:/app/abilities.json:ro
      - ./quarry/post_processed_items.json:/app/items.json:ro
      - ./hammer/hammer.db3:/app/data/hammer.db3
    environment:
      - RUST_LOG=hammer=trace,tower_http=trace
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  # Frontend service (Next.js)
  frontend:
    build:
      context: .
      dockerfile: chisel/Dockerfile
    container_name: chisel-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=0
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

# Custom network for service communication
networks:
  app-network:
    driver: bridge
