interface Config {
  SERVER_API_ENDPOINT: string;
  GOOGLE_CLIENT_ID: string;
  GOOGLE_PROJECT_ID: string;
  GOOGLE_AUTH_URI: string;
  GOOGLE_TOKEN_URI: string;
  GOOGLE_CLIENT_SECRET: string;
  GOOGLE_REDIRECT_URI: string;
  NEXTJS_API_URL: string;
}
export default {
  SERVER_API_ENDPOINT: process.env.SERVER_API_ENDPOINT,
  GOOGLE_CLIENT_ID: process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID,
  GOOGLE_PROJECT_ID: process.env.GOOGLE_PROJECT_ID,
  GOOGLE_AUTH_URI: process.env.GOOGLE_AUTH_URI,
  GOOGLE_TOKEN_URI: process.env.GOOGLE_TOKEN_URI,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI: process.env.NEXT_PUBLIC_GOOGLE_REDIRECT_URI,
  NEXTJS_API_URL: process.env.NEXT_PUBLIC_API_ENDPOINT,
} as Config;
